/*
project euler problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/
#include <iostream>
using namespace std;

const int Max = 4000000;

int fib(int i)
{
	if(i == 1)
	{
		return 1;
	}
	else if(i == 2)
	{
		return 2;
	}
	else
	{
		return fib(i - 1) + fib(i - 2);
	}
}

int main()
{
	int i, sum;

	for(i = 1, sum = 0; fib(i) <= Max; ++i)
	{
		if((fib(i) % 2) == 0)
		{
			sum += fib(i);
		}
	}
	cout << sum << endl;

	return 0;
}
